config/routes.rb
Rails.application.routes.draw do
  resources :shift_details
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users

  root :to => 'home#index'
end

app/models/shift_detail.rb
class ShiftDetail < ActiveRecord::Base
  belongs_to :user, inverse_of: :shift_details
  delegate :name, to: :user, allow_nil: true
  scope :morning_shifts, -> { where("start_time < '2015-10-13 12:00' and start_time > 
                            '2015-10-13 00:00'")}
 # do
 #   def test_value
 #     "actual value"
 #   end
 # end
end

app/controllers/shift_details_controller.rb
class ShiftDetailsController < ApplicationController
  load_and_authorize_resource
  before_action :set_shift_detail, only: [:show, :edit, :update, :destroy]

  # GET /shift_details
  # GET /shift_details.json
  def index
    @shift_details = ShiftDetail.where(user: current_user)
  end

  # GET /shift_details/1
  # GET /shift_details/1.json
  def show
  end

  # GET /shift_details/new
  def new
    @shift_detail = ShiftDetail.new
  end

  # GET /shift_details/1/edit
  def edit
  end

  # POST /shift_details
  # POST /shift_details.json
  def create
    @shift_detail = ShiftDetail.new(shift_detail_params)
    @shift_detail.user_id = current_user.id
    respond_to do |format|
      if @shift_detail.save
        format.html { redirect_to @shift_detail, notice: 'Shift detail was successfully created.' }
        format.js {render :create, notice: 'Shift detail was successfully created.'}
        #format.js { render :show, status: :created, location: @shift_detail }
      else
        format.html { render :new }
        format.json { render json: @shift_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shift_details/1
  # PATCH/PUT /shift_details/1.json
  def update
    shift_detail_params[:user_id] = current_user.id
    respond_to do |format|
      if @shift_detail.update(shift_detail_params)
        format.html { redirect_to @shift_detail, notice: 'Shift detail was successfully updated.' }
        #format.json { render :show, status: :ok, location: @shift_detail }
        format.json {redirect_to @shift_detail, notice: 'Shift detail was successfully created.'}
      else
        format.html { render :edit }
        format.json { render json: @shift_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shift_details/1
  # DELETE /shift_details/1.json
  def destroy
    @shift_detail.destroy
    respond_to do |format|
      format.html { redirect_to shift_details_url, notice: 'Shift detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift_detail
      @shift_detail = ShiftDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_detail_params
      params.require(:shift_detail).permit(:shift_name, :start_time, :end_time, :description, :user_id)
    end
end

app/helpers/shift_details_helper.rb
module ShiftDetailsHelper
end

app/views/shift_details/_form.html.erb
<%= form_for(@shift_detail)do |f| %>
  <% if @shift_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift_detail.errors.count, "error") %> prohibited this shift_detail from being saved:</h2>

      <ul>
      <% @shift_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shift_name %><br>
    <%= f.text_field :shift_name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shift_details/_list_details.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shift Details</h1>

<table>
  <thead>
    <tr>
      <th>Shift name</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shift_details.each do |shift_detail| %>
      <tr>
        <td><%= shift_detail.shift_name %></td>
        <td><%= shift_detail.start_time %></td>
        <td><%= shift_detail.end_time %></td>
        <td><%= shift_detail.description %></td>
        <td><%= shift_detail.name%></td>
        <td><%= link_to 'Show', shift_detail %></td>
        <td><%= link_to 'Edit', edit_shift_detail_path(shift_detail) %></td>
        <td><%= link_to 'Destroy', shift_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Shift detail', new_shift_detail_path %>

app/views/shift_details/create.js.erb
document.body.html("<%= j (render @shift_details) %>");
$('#shift-form').slideUp(350);

app/views/shift_details/edit.html.erb
<h1>Editing Shift Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift_detail %> |
<%= link_to 'Back', shift_details_path %>

app/views/shift_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shift Details</h1>

<table>
  <thead>
    <tr>
      <th>Shift name</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shift_details.each do |shift_detail| %>
      <tr>
        <td><%= shift_detail.shift_name %></td>
        <td><%= shift_detail.start_time %></td>
        <td><%= shift_detail.end_time %></td>
        <td><%= shift_detail.description %></td>
        <td><%= shift_detail.name%></td>
        <td><%= link_to 'Show', shift_detail %></td>
        <td><%= link_to 'Edit', edit_shift_detail_path(shift_detail) %></td>
        <td><%= link_to 'Destroy', shift_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Shift detail', new_shift_detail_path %>

app/views/shift_details/index.js.erb
$('#shift-details').html("<%= j (render 'list_details') %>");
$('#shift-details').slideDown(350);
$('#shift-form').slideUp(350);

app/views/shift_details/new.html.erb
<h1>New Shift Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', shift_details_path %>

app/views/shift_details/new.js.erb
$('#shift-form').html("<%= j (render 'form', remote: true) %>");
$('#shift-form').slideDown(350);
$('#shift-details').slideUp(350);

app/views/shift_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shift name:</strong>
  <%= @shift_detail.shift_name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shift_detail.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift_detail.end_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shift_detail.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift_detail.name%>
</p>

<%= link_to 'Edit', edit_shift_detail_path(@shift_detail) %> |
<%= link_to 'Back', shift_details_path %>